### ISSUE TITLE
Success in twinBASIC! Few very minor issues...

### ISSUE THREAD

**Issue by GCuser99** [sihlfall/vba-regex#1]
Wow - this is awesome to see that someone has tackled this, especially given the uncertain future of Microsoft VBScript Regular Expressions. Thank you!

I was able to generate the aio version and then import into [twinBASIC](https://twinbasic.com/preview.html) without problems. Tested (64-bit) the examples in your .md and all worked ~~except for Example 3, which printing blank lines to Debug window. I will take a closer look at that when I have some time and report back~~.

One thing twinBASIC IDE does by default is flag (warning only) functions and variables that are not explicitly typed (implied Variants). Here is what got flagged:

Following functions are not explicitly typed:
Unionize
LexerParseLegacyOctal
UnicodeReIsWordchar
TryInitializeRegex

Input arguments localMatch and multiline in procedure InitializeMatcherState are not explicitly typed
Input argument stepsLimit in procedure DfsMatch not explicitly typed

It's not a big deal but I'm wondering if you can clean those up in future so that those warning go away?

Anyway, exciting and bravo!

**Comment by sihlfall** [comment]
Resolved by [6057b5a](https://github.com/sihlfall/vba-regex/commit/6057b5a2c1062db7bec1a839507e8ae4a74e4a74)
